#!/bin/sh

srcfile=file.c
cat - > $srcfile <<EOF
#ifdef GCC
#define ptr_t int *
#endif

int main ()
{
  int a = 45;
  ptr_t a_ptr = &a;
  printf ("%d\n", *a_ptr);
  return 0;
}
EOF

ret=0
. $srcdir/tester.sh
rm $srcfile
exit $ret
