#!/bin/sh

srcfile=file.c
cat - > $srcfile <<EOF
int main () {
  int t = 10;
  if (t < 20) {
    if (t > 9) {
      t = 32;
    }
  }
  printf ("%d\n", t);
  return 0;
}
EOF

ret=0
. $srcdir/tester.sh
rm $srcfile
exit $ret
