#!/bin/sh

src='
int test2 (int b) {
    return b + 1;
}

int main () {
    printf ("%d\n", test2 (3));
    return 0;
}

'

ret=0
srcfile=`mktemp --suffix=.c`
echo "$src" > $srcfile

./tester.sh $srcfile $0 || ret=1

rm $srcfile
exit $ret
