#!/bin/sh

srcfile=file.c
cat - > $srcfile <<EOF
int main ()
{
  int a = 0;
  if (a > 0)
    puts ("First Condition");
  else if (a < 0)
    puts ("Second Condition");
  else
    puts ("Third Condition");
  return 0;
}
EOF

ret=0
. ./tester.sh
rm $srcfile
exit $ret
