#!/bin/sh

src='
int foo (int a, int b) {
    return a << b;
}

int main () {
    printf ("%d\n", foo (3, 4));
    return 0;
}    
'

ret=0
srcfile=file.c
echo "$src" > $srcfile

./tester.sh $srcfile $0 || ret=1

rm $srcfile
exit $ret
