#!/bin/sh

srcfile=file.c
cat - > $srcfile <<EOF
int test2 (int b) {
    return b + 1;
}

int main () {
    printf ("%d\n", test2 (3));
    return 0;
}
EOF

ret=0

. $srcdir/tester.sh

rm $srcfile
exit $ret
