#!/bin/sh

srcfile=file.c
cat - > $srcfile <<EOF
int main ()
{
  int a = 1892;
  int b = 648;
  while (b != 0)
    {
      int t = a % b;
      a = b;
      b = t;
    }
  printf ("%d\n", a);
  return 0;
}
EOF

ret=0
. ./tester.sh
rm $srcfile
exit $ret
