#!/bin/sh

ret=0
srcfile=file.c
cat - > $srcfile <<EOF
int foo (int a) {
    return a;
}

int bar (int a) {
    return 1 + 1 + foo (a);
}

int main () {
    printf ("%d\n", bar (0));
    return 0;
}
EOF

./tester.sh $srcfile $0 || ret=1

rm $srcfile
exit $ret
