#!/bin/sh

src='
int test4 (int a) {
    while (a < 20) {
	a = a + 1;
    }
    return a;
}

int main () {
    printf ("%d\n", test4 (3));
    printf ("%d\n", test4 (-1));
    printf ("%d\n", test4 (20));
    printf ("%d\n", test4 (21));
    return 0;
}
'

ret=0
srcfile=`mktemp --suffix=.c`
echo "$src" > $srcfile

./tester.sh $srcfile $0 || ret=1

rm $srcfile
exit $ret
