#!/bin/sh

src='
int foo (int a) {
    return a;
}

int bar (int a) {
    return 1 + 1 + foo (a);
}

int main () {
    printf ("%d\n", bar (0));
    return 0;
}
'

ret=0
srcfile=`mktemp --suffix=.c`
echo "$src" > $srcfile

./tester.sh $srcfile || ret=1

rm $srcfile
exit $ret
