#!/bin/sh

src='
int test5 (int a) {
  return 3 * 3 + (5 % 3 % 2) * 4 * 4;
}

int main () {
    printf ("%d\n", test5 (2));
    return 0;
}
'

ret=0
srcfile=`mktemp --suffix=.c`
echo "$src" > $srcfile

./tester.sh $srcfile || ret=1

rm $srcfile
exit $ret
